### ISSUE TITLE
'npx typewriter init' fails with error 'setRawMode is not a function'

### ISSUE THREAD

**Issue by DominikFra** [segmentio/typewriter#139]
I'm trying to use typewriter
When trying to create a typewiter.yml with the command `npx typewriter init` I am getting the error message:

  ✖ Error: An unexpected error occurred.
   → setRawMode is not a function

I'm using MacOS
node: v12.18.3
npx: 6.14.6
typewriter: 7.1.0

**Comment by jedvalmar** [comment]
@DominikFra  I had the same issue and was able to make typewriter work by using `npx typewriter@next init` instead.

Using MacOS
node: v12.18.4
npx: 6.14.6
typewriter: 7.1.0

**Comment by Duder-onomy** [comment]
Same issue, 
@jedvalmar work-around does not fix things for me. 

Osx
Node: 15.11.0
npx: 7.6.0
typewriter: 7.4.1

**Comment by vianch** [comment]
Same here
OSX
node 14.15.5
typewriter 741

**Comment by Duder-onomy** [comment]
Ok, mine just started working.  Here is what changed

* We didn't have ANY API tokens configured in the workspace, so we configured 1, the same I used to successfully run `npx typewriter init` later.   ...I suppose I expected to be prompted to make a token in the segment gui? 
* I manually created this `typewriter.yml` 

```
scripts:
  token: <1234ABCD123ABC12AB1A>
client:
  sdk: analytics.js
  language: typescript
trackingPlans:
  - id: <ABCDEFG......>
    workspaceSlug: <sluglife>
    path: ./analytics
```

After those 2 changes, I was able to run `npx typewriter init`
