### ISSUE TITLE
"trackingPlans[0].workspaceSlug" is not allowed

### ISSUE THREAD

**Issue by correttojs** [segmentio/typewriter#261]
Migrating to typewriter version 8

Here is my `typewriter.yml`
```
trackingPlans:
  - id: XXX
    workspaceSlug: myslug.com
    path: ./src/typewriter
```
Run `typewriter update`

The following error is reported: `"trackingPlans[0].workspaceSlug" is not allowed`
